### ISSUE TITLE
Bug: OS X 10.11.4 - Can't focus windows without a dock icon

### ISSUE THREAD

**Issue by ghost** [beniamino38/isolator#2]
Can't focus (bring to the foreground) windows without a dock icon when **Hide windows of other applications** is enabled. A simple test is to enable that option and and select **About This Mac** in the Apple menu.

I use this option since I started using Isolator years ago, to mimic Single Application Mode and keep an uncluttered desktop.

@beniamino38 Thank you for developing Isolator and picking it up again after these many years. Never lost hope for an update for newer OS Xs. Serious kudos to you.

**Comment by ben-willmore** [comment]
Thanks for the kind remarks! Can you confirm whether the bug is new in 4.99beta, and/or whether it's new to OSX 10.11?

**Comment by ghost** [comment]
It's new to OS X 10.11. Version 4.79b worked well in OS X 10.9 while both version 4.79b and 4.99b have the same behavior on OS X 10.11.

**Comment by ghost** [comment]
There's a similar app called [Hides](https://www.macupdate.com/app/mac/42726/hides) and according to the latest release notes:

> Now requires OS X 10.10 or later
> Fixed issue with system password windows constantly losing focus in single-app mode

System password windows are an example of windows without a dock icon but now I realize that maybe this can only be fixed if Isolator requires OS X 10.10 or later too, which can be undesirable for some users.
