### ISSUE TITLE
no way to access isolator after dismissing menu bar icon

### ISSUE THREAD

**Issue by zzhjerry** [beniamino38/isolator#4]
After I removed the menu bar icon for isolator, I'm not able to open preference setting anymore. The app is working but I just can "open" any parts of its window anymore. The only way to quit it is using "activity monitor"

Is this a bug for my own computer or this app?

**Comment by ben-willmore** [comment]
This is the intended behaviour. To get the preferences window up, use command-option-shift-I (or add option to your custom key combination).
